server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: aike123
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/emps
